### ISSUE TITLE
pyroms.tools has no attribute 'section'

### ISSUE THREAD

**Issue by han348661657** [ESMG/pyroms#17]
In the  pyroms/tools.py, the latslice() function used pyroms.tools.section() to get the  latslice, but there is no **section()** in the tools.py.
How did to rebuild pyroms.tools.section() ?

**Comment by bilgetutak** [comment]
I believe it should be pyroms.tools.transect() function. As far as I can remember, I modified it to be transect() function and it works without problem.

**Comment by han348661657** [comment]
Thinks, I changed **pyroms.tools.section** to **pyroms.tools.transect** in tools.py, and 
modified `near = np.zeros(((j1-j0+1),4))` to `near = np.zeros(((j1-j0+1),4), dtype=int)`.
Now, it works!
