### ISSUE TITLE
Arctan issue with make_tide

### ISSUE THREAD

**Issue by fdufois** [ESMG/pyroms#41]
Hi,
I might be missing something but I think that there is an issue in make_tide.py.
After comparing with the outputs from the croco_tools I noticed that the phases were all between -90 and 90°. 
I think np.arctan2 should be used instead of np.arctan to correct the issue. The results are pretty similar now (considering the TPXO version used in the croco_tools is different (v7)).
Please let me know if I'm wrong.
Thanks

**Comment by kshedstrom** [comment]
Yes, I'm sure you are right. I just pushed the change. Can you confirm that I got it right? In future, the recommended approach is a pull request.

**Comment by fdufois** [comment]
It's all good now. Thanks for pushing that.
