### ISSUE TITLE
Lots of hard-coded /u1/uaf/kshedstrom/ paths

### ISSUE THREAD

**Issue by drf5n** [ESMG/pyroms#5]
There are a lot of hard-coded /u1/uaf/kshedstrom/ paths in the installation scripts and makefiles, which makes it hard to try out the code.

For example: 

https://github.com/ESMG/pyroms/blob/master/pyroms/install_pyroms.sh#L4 

and 

https://github.com/ESMG/pyroms/blob/1baa7a0fa06ae60d4c1c2a7dca6f064f0c7618d3/pyroms/external/gridutils/makefile#L10

Maybe in the makefiles it would be nice to replace them with some flavor of `${DESTDIR}` ?

**Comment by kshedstrom** [comment]
The idea is that you need to modify install_pyroms.sh before executing it (or cutting and pasting from it into another window). The files down under external should take care of themselves. Still, getting the shared libraries to load is tricky and I don't always succeed.

Current active development is being done on the ESMG/PyCNAL project, one goal being to limit (eliminate?) the need for shared libraries.

**Comment by drf5n** [comment]
I first tried modding $DESTDIR in  install_pyroms.sh, but then the hardcoded paths in external/* makefiles caused a stream of errors.

Ah, I missed two things: 
  1) install_pyroms.sh calls configure, and all the extern/*/makefile files are regenerated.
  2) DESTDIR needs to be an absolute path.
