### ISSUE TITLE
the problem when running make_remap_weight_file.py 

### ISSUE THREAD

**Issue by wjlyx** [ESMG/pyroms#54]
I encountered this problem when running make_remap_weight_file.py How can I solve it?
![image](https://github.com/ESMG/pyroms/assets/113485155/23195d1e-de51-49f4-a110-32f888585303)

**Comment by kshedstrom** [comment]
It looks like you are remapping between NEP and EastSea? NEP is Northeast Pacific and does not cover the East Sea.

1. pyroms as a package is barely supported these days.
2. The make_remap_weights_file is used with scrip, which is definitely not supported these days.
3. We never supported remapping between different parts of the globe. Make sure you download the patch you want.
